services:
  db:
    image: postgres:16
    container_name: tgads_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: telegram_monitoring
      POSTGRES_USER: pinchik
      POSTGRES_PASSWORD: qwerty123
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pinchik -d telegram_monitoring"]
      interval: 5s
      timeout: 5s
      retries: 20

  bot:
    build: .
    container_name: tgads_bot
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    command: ["python", "-m", "src.main_bot"]

  worker:
    build: .
    container_name: tgads_worker
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    # Важно: Telethon создаёт session-файл. Чтобы он сохранялся между перезапусками:
    volumes:
      - telethon_session:/app
    command: ["python", "-m", "src.main_worker"]

volumes:
  pgdata:
  telethon_session:
